Pin version of tox to 2.1.1
They broke our stuff again.  Now (on 2.2.1) it's saying something like...

ValueError: ('testenv', 'setenv') already in [('testenv:lsf', 'setenv'),
('testenv', 'setenv'), ('testenv:lsf', 'setenv')]